<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.2" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>f52d4ae4-7080-465a-a360-6de531525494</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.MongoDB" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Web\NeoReports.Samples.AspireMongoDbWide.Web.csproj" />
  </ItemGroup>

</Project>
