<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <Description>Amazon S3 destination for NeoReports.</Description>
    <PackageTags>reports;reporting;destination;s3;aws</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NeoReports.Abstractions\NeoReports.Abstractions.csproj" />
    <ProjectReference Include="..\..\NeoReports.Core\NeoReports.Core.csproj" />
    <ProjectReference Include="..\..\Destinations\NeoReports.Destinations.Local\NeoReports.Destinations.Local.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
  </ItemGroup>

</Project>
