<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <Description>Local filesystem destination for NeoReports.</Description>
    <PackageTags>reports;reporting;destination;filesystem</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NeoReports.Abstractions\NeoReports.Abstractions.csproj" />
    <ProjectReference Include="..\..\NeoReports.Core\NeoReports.Core.csproj" />
  </ItemGroup>

</Project>
